src/Blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("posts.urls", namespace='posts')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify


from markdown_deux import markdown
from comments.models import Comment


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1

    return "Post-%s/%s" %(new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, 
            null=True, 
            blank=True, 
            )

    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=True))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

src/posts/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except: 
    pass


from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post



def post_create(request):
	if not request.user.is_authenticated():
		raise Http404
		
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()

		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)

def post_detail(request, slug=None):
	
	instance = get_object_or_404(Post, slug=slug)

	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id
	}
	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid() and request.user.is_authenticated():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get('object_id')
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None

		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()


		new_comment, created = Comment.objects.get_or_create(
							user = request.user,
							content_type= content_type,
							object_id = obj_id,
							content = content_data,
							parent = parent_obj,
						)
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())


	comments = instance.comments
	context = {
		"title": instance.title,
		"instance": instance,
		"comments": comments,
		"comment_form":form,
	}
	return render(request, "post_detail.html", context)

def post_list(request):

	queryset_list = Post.objects.active() 
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()
	
	query = request.GET.get("q")

	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)
				).distinct()

	paginator = Paginator(queryset_list, 8) # Show 8 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"object_list": queryset, 
		"title": "List",
		"page_request_var": page_request_var,
	}
	return render(request, "post_list.html", context)


def post_update(request, slug=None):

	instance = get_object_or_404(Post, slug=slug)

	if instance.user != request.user:
		reponse = HttpResponse("You do not have permission to do this.")
		return reponse	


	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	
	return render(request, "post_form.html", context)



def post_delete(request, slug=None):

	instance = get_object_or_404(Post, slug=slug)
	if instance.user != request.user:
		reponse = HttpResponse("You do not have permission to do this.")
		return reponse

	if request.method == "POST":
		instance.delete()
		return redirect("posts:list")
	context = {
        		"object": instance
	}
	return render(request, "confirm_delete.html", context)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Jamie's Blog</title>

    <!-- Bootstrap Core CSS -->
    <!-- <link href="https://blackrockdigital.github.io/startbootstrap-blog-post/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel=stylesheet type="text/css" href="/static/css/bootstrap.min.css">
<!--     <link rel=stylesheet type="text/css" href="https://blackrockdigital.github.io/startbootstrap-blog-post/vendor/bootstrap/css/bootstrap.min.css"> -->


    <!-- Custom CSS -->
    <link rel=stylesheet type="text/css" href="/static/css/blog-post.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block head_extra %}{% endblock head_extra %}

</head>

<body>

    <!-- Navigation -->
<!--     <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container"> -->
            <!-- Brand and toggle get grouped for better mobile display -->
<!--             <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="font-family:monospace; font-size: 26px" href="{% url 'posts:list' %}">Home</a>
            </div> -->
            <!-- Collect the nav links, forms, and other content for toggling -->
<!--             <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav" >
                        {% if not request.user.is_authenticated %}
                        <li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
                        <li class="pull-right"><a href="{% url 'login' %}">Login</a></li>
                        {% else %}
                        <li class="pull-right"><a href="{% url 'logout' %}">Logout</a></li>
                        <li class="pull-right" ><a href="{% url 'posts:create' %}"><span class="glyphicon glyphicon-plus" aria-hidden=true></span> <span class=glyphicon-class>Post</span> </a></li>
                        {% endif %}
                </ul>

            </div> -->
            <!-- /.navbar-collapse -->

            

<!--         </div> -->
        <!-- /.container -->
<!--     </nav> -->


    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'posts:list' %}">Jamie's Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'posts:list' %}">Home <span class="sr-only">(current)</span></a>
                </li>

                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a  class="nav-link"  href="{% url 'login' %}">Login</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:create' %}">Hi {{request.user}} ~   Create Post ! </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>



{% block content %}{% endblock content %}

    <!-- jQuery -->
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
    
    <!-- Bootstrap Core JavaScript -->
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="/static/js/popper.min.js"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

<script type="text/javascript">
$(document).ready(function(){
    $(".content-markdown").each(function(){
            var content = $(this).text()
            var markedContent = marked(content)
            $(this).html(markedContent)
    })

        $(".post-detail-item img").each(function(){
            $(this).addClass("img-responsive").css("width", "690")
                })

        $(".comment-reply-btn").click(function(event){
                event.preventDefault()
                $(this).parent().next(".comment-reply").fadeToggle()
        })


})
</script>



</body>

</html>

src/templates/comment_thread.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}


{% block content %}
{{ object }}

</br>
<div class="col-lg-8">
                    <div class="media mb-4" style="position: relative; left: 30px; ">
                    <img class="d-flex mr-3 rounded-circle" src="{{ comment.user.userprofile.avatar.url }}" width="50" height="50" alt="">
                    <div class="media-body">
                        <h5 class="mt-0">{{ comment.user }}</h5> {{ comment.content }}
                        <footer class="blockquote-footer">{{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} {% endif %}  {% if request.user == comment.user %}<a href='{{ comment.get_delete_url }}'>Delete</a> {% endif %}</footer>

                        <div>
                        {% for child_comment in comment.children %}
                   

                          <div class="media mt-4">
                              <img class="d-flex mr-3 rounded-circle" src="{{ child_comment.user.userprofile.avatar.url }}" width="50" height="50" alt="">
                              <div class="media-body">
                                  <h5 class="mt-0">{{ child_comment.user }}</h5> {{ child_comment.content }}
                                  <footer class="blockquote-footer">{{ comment.timestamp|timesince }} ago {% if request.user == child_comment.user %}<a href='{{ child_comment.get_delete_url }}'>Delete</a>{% endif %}</footer>
                              </div>
                          </div>

                        {% endfor %}

                         {% if request.user.is_authenticated %}
                          <form method="POST" action="."> {% csrf_token %}
                            {{ form|crispy }}
                            <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                            <input type='submit' value='Reply' class='btn btn-default'>
                          </form>
                          {% else %}
                          <p>You must login to comment </p>
                          {% endif %}


                        </div>

                        </div>
                        </div>
</div>



{% endblock content %}

src/templates/confirm_delete.html
{% extends "base.html" %}
{
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}

</br>
<div class='col-sm-6 col-sm-offset-3' style="margin: 0px auto">
  <h1>Confirm Delete</h1>
        
      
            <form method="POST" action="."> {% csrf_token %}
                <p>A re you sure you want to delete: "{{ object.content }}"?</p>
              
                <input type='submit' value='Confirm' class='btn btn-warning'>
                <a href='{{ object.get_absolute_url }}' class='btn btn-default'>Cancel</a>
            </form>
 

    

        <hr/>
</div>


{% endblock content %}

src/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3' style="margin: 0px auto">
<h1>{{ title }}</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ user_form|crispy }}

{% if  profile_form %}
	{{ profile_form|crispy }}
{% endif %}

<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}

src/templates/post_detail.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}


<!--  {% block post_detail_link %}
  <li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
  {% endblock %} -->

  {% block content %}

      <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                 <h1 class="mt-4">{{ title }}</h1>


                <!-- Author -->
                <p class="lead">
                    by {{ instance.user }}  
                    <a href="{% url 'posts:update' slug=instance.slug %}" class='btn btn-default'>Edit</a>
                    <a href="{% url 'posts:delete' slug=instance.slug %}" class='btn btn-warning'>Delete</a>

                </p>

                <hr>

                <!-- Date/Time -->
                <p> Posted on {{ instance.publish }}</p>

                <hr>

                <!-- Preview Image -->
                    {% if instance.image %}
                       <img class="img-fluid rounded" src='{{ instance.image.url }}'  alt="">
                    {% endif %}

                <hr>

                <!-- Post Content -->
                <div class='post-detail-item '>{{ instance.get_markdown }}</div>

                <hr>

                <!-- Blog Comments -->

                <!-- Comments Form -->
                
                <div class="card my-4">
                    {% if request.user.is_authenticated %}
                    <h5 class="card-header">Leave a Comment:</h5>
                    <div class="card-body">
                    <form method="POST" action="."> {% csrf_token %}
                        <div class="form-group">
                              {{ comment_form|crispy }}
                            <!-- <textarea class="form-control" rows="3"></textarea> -->
                        </div>
                        <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                        <input type='submit' value='Reply' class='btn btn-primary'>
                    </form>

                     {% else %}
                      <p>You must login to comment </p>
                     {% endif %}

                     </div>

                </div>

<!--                <div class="card my-4">
                    <h5 class="card-header">Leave a Comment:</h5>
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <textarea class="form-control" rows="3"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div> -->



                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                    {% for comment in comments %}

                    <div class="media mb-4">
                    <img class="d-flex mr-3 rounded-circle" src="{{ comment.user.userprofile.avatar.url }}" width="50" height="50"  alt="">
                    <div class="media-body">
                        <h5 class="mt-0">{{ comment.user }}</h5> {{ comment.content }}
                        <footer class="blockquote-footer">{{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %} <a class='comment-reply-btn' href='#'>Reply</a> | <a class='' href='{{ comment.get_absolute_url }}'>Thread</a></footer>

                        <div class='comment-reply'>
                        {% for child_comment in comment.children %}
                   

                          <div class="media mt-4">
                              <img class="d-flex mr-3 rounded-circle" src="{{ child_comment.user.userprofile.avatar.url }}" width="50" height="50" alt="">
                              <div class="media-body">
                                  <h5 class="mt-0">{{ child_comment.user }}</h5> {{ child_comment.content }}
                                 <footer class="blockquote-footer">{{ comment.timestamp|timesince }} ago</footer>
                              </div>
                          </div>

                        {% endfor %}

                         {% if request.user.is_authenticated %}
                          <form method="POST" action="."> {% csrf_token %}
                            {{ comment_form|crispy }}
                            <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                            <input type='submit' value='Reply' class='btn btn-default'>
                          </form>
                          {% else %}
                          <p>You must login to comment </p>
                          {% endif %}


                        </div>

                        </div>
                        </div>

                      {% endfor %}

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">



        </div>
        <!-- /.row -->

        <hr>



    </div>
    <!-- /.container -->

    {% endblock content %}

src/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %} 
{{ form.media }}

{% endblock head_extra %}


{% block content %}

<div class='col-sm-6 col-sm-offset-3' style="margin: 0px auto">
	<h1>Post Form</h1>
	<hr/>
	<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
		{{ form|crispy }}
		<input type='submit' class='btn btn-default' value='Create Post' />
	</form>
</div>

{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}
{% block content %}


    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

             <h1 class="my-4">Post List</h1>


            {% for obj in object_list %}


                <div class="card mb-4 ">
                    {% if obj.image %}
                    <img class="card-img-top"  src='{{ obj.image.url }}' alt="Card image cap">
                    {% endif %}
                    <div class="card-body post-detail-item">
                        <h2 class="card-title">{{ obj.title }}</h2>
                        <p class="card-text ">{{ obj.get_markdown|truncatechars_html:120 }}</p>
                        <a href="{{ obj.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                    <div class="card-footer text-muted">
                        Posted on {{ obj.publish }} by {{ obj.user }}
                    </div>
                </div>

            {% endfor %}




                <div class="pagination">
                    <span class="step-links"  style="font-size: 18px">
                        {% if object_list.has_previous %}
                            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                        </span>

                        {% if object_list.has_next %}
                            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                        {% endif %}
                    </span>
                </div>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
<!--                 <div class="well">
                    <h4>Blog Search</h4>
                    <form method='GET' action='' class='row'>
                    <div class="input-group">
                        <input type="text" class="form-control" name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                    </form> -->
                    <!-- /.input-group -->
<!--                 </div> -->

                <div class="card my-4">
                    <h5 class="card-header">Blog Search</h5>
                    <div class="card-body">
                       <form method='GET' action='' class='row'>
                        <div class="input-group">
                            <input type="text" class="form-control" name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
                            <span class="input-group-btn">
                                <button class="btn btn-secondary" type="submit">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>

                <!-- Blog Categories Well -->
<!--                 <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div> -->
                    <!-- /.row -->




                <!-- Side Widget -->
                <div class="card my-4">
                    <h5 class="card-header">About me</h5>
                    <div class="card-body">
                        I'm Jamie. This is my first Blog
                    </div>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>



    </div>
    <!-- /.container -->


{% endblock content %}